import 'package:hive_flutter/hive_flutter.dart';
import '../../models/user_model.dart';
import '../../models/project_model.dart';
import '../../models/task_model.dart';
import '../../models/enums.dart';

class HiveService {
  static const String usersBoxName = 'users';
  static const String projectsBoxName = 'projects';
  static const String tasksBoxName = 'tasks';
  static const String settingsBoxName = 'settings';

  static Future<void> init() async {
    await Hive.initFlutter();

    // Register Adapters
    // Note: These will be generated by build_runner
    Hive.registerAdapter(TaskStatusAdapter());
    Hive.registerAdapter(TaskPriorityAdapter());
    Hive.registerAdapter(ProjectStatusAdapter());
    Hive.registerAdapter(UserModelAdapter());
    Hive.registerAdapter(ProjectModelAdapter());
    Hive.registerAdapter(TaskModelAdapter());

    // Open Boxes
    await Hive.openBox<UserModel>(usersBoxName);
    await Hive.openBox<ProjectModel>(projectsBoxName);
    await Hive.openBox<TaskModel>(tasksBoxName);
    await Hive.openBox(settingsBoxName);
  }

  // Generic methods for Hive operations
  static Box<T> getBox<T>(String name) {
    return Hive.box<T>(name);
  }
}
